import type {AuditEntry} from '../audit-utils';
import type {ReconciliationIssue} from '../workflow-utils';

type AuditView={healthy:boolean;entries:number;files:number;legacyFiles:number;firstTimestamp?:string;lastTimestamp?:string;headHash:string;recent:AuditEntry[]};
type ReleaseHealthRecord={generatedAtUtc:string;applicationVersion:string;ruleSetVersion:string;operator:string;systemName:string;mappedFolder:string;databaseSavedUtc:string;backupCreatedUtc:string;backupFilename:string;auditEntries:number;auditHeadHash:string;status:'Verified';recordSha256:string};

export function ReconciliationModal({issues,loading,error}:{issues:ReconciliationIssue[];loading:boolean;error:string}){const high=issues.filter(issue=>issue.severity==='High').length;return <><p className="eyebrow">Mapped-Folder Integrity</p><h2>Reconciliation Center</h2><p className="hint">Compares active evidence with manifest records and highlights discrepancies. No files or records are changed.</p>{loading&&<div className="empty">Scanning and reconciling evidence…</div>}{error&&<p className="restore-warning"><b>Reconciliation Failed:</b> {error}</p>}{!loading&&!error&&<><div className="audit-summary"><span><b>{issues.length}</b>Total Issues</span><span><b>{high}</b>High Priority</span><span><b>{issues.length-high}</b>Review</span></div><div className="reconciliation-list">{issues.map(issue=><article key={issue.id} className={issue.severity.toLowerCase()}><div><strong>{issue.category}</strong><span className={`status ${issue.severity==='High'?'overdue':'due'}`}>{issue.severity}</span></div><p>{issue.summary}</p><small>{issue.detail}{issue.path&&<><br/><code>{issue.path}</code></>}</small></article>)}{!issues.length&&<div className="empty">No reconciliation issues were found.</div>}</div></>}</>}

export function AuditLogModal({view,loading,error}:{view:AuditView|null;loading:boolean;error:string}){return <><p className="eyebrow">Read-Only Audit Evidence</p><h2>Audit Log</h2><p className="hint">The complete hash chain is verified before entries are displayed. Viewing the log does not add an audit entry.</p>{loading&&<div className="empty">Verifying Audit Log…</div>}{error&&<p className="restore-warning"><b>Integrity Check Failed:</b> {error}</p>}{view&&!loading&&!error&&<><div className="audit-summary"><span><b>{view.entries}</b>Total Entries</span><span><b>{view.files}</b>Daily Files</span><span><b>{view.lastTimestamp?new Date(view.lastTimestamp).toLocaleString():'—'}</b>Latest Entry</span></div>{view.recent.length?<div className="audit-list">{view.recent.map(entry=><article key={entry.entryHash}><div><strong>#{entry.sequence} · {new Date(entry.timestampUtc).toLocaleString()}</strong><small>{entry.actor}</small></div><p>{entry.action}</p><code>{entry.entryHash}</code></article>)}</div>:<div className="empty">No audit entries have been recorded for this information system.</div>}{view.entries>view.recent.length&&<p className="hint">Showing the newest {view.recent.length} of {view.entries} verified entries.</p>}</>}</>}

export function ReleaseHealthModal({record,loading,error,onDownload}:{record:ReleaseHealthRecord|null;loading:boolean;error:string;onDownload:()=>void}){return <><p className="eyebrow">Release and Evidence Integrity</p><h2>Release Health</h2><p className="hint">Verifies the current database, newest checksum-protected backup, and tamper-evident audit chain. This view is read-only.</p>{loading&&<div className="empty">Verifying Release Health…</div>}{error&&<p className="restore-warning"><b>Release Health Failed:</b> {error}</p>}{record&&<><div className="provenance-grid"><span>Status<b>{record.status}</b></span><span>Generated UTC<b>{record.generatedAtUtc}</b></span><span>Application Version<b>{record.applicationVersion}</b></span><span>Rule-Set Version<b>{record.ruleSetVersion}</b></span><span>Windows Operator<b>{record.operator}</b></span><span>Information System<b>{record.systemName}</b></span><span className="span2">Mapped Folder<b>{record.mappedFolder}</b></span><span>Database Saved UTC<b>{record.databaseSavedUtc}</b></span><span>Backup Created UTC<b>{record.backupCreatedUtc}</b></span><span className="span2">Verified Backup<b>{record.backupFilename}</b></span><span>Audit Entries<b>{record.auditEntries}</b></span><span className="span2">Audit Head Hash<code>{record.auditHeadHash}</code></span><span className="span2">Integrity Record SHA-256<code>{record.recordSha256}</code><small>Checksum protected; this is not a digital signature.</small></span></div><button className="primary full" onClick={onDownload}>Download Integrity Record</button></>}</>}
