import './user-guide.css';

const formats = [
  ['System Access Request', 'Last_First (ORG) SAAR DDMMMYYYY'],
  ['DoD Cyber Awareness', 'Last_First (ORG) DoD Cyber Cert DDMMMYYYY'],
  ['General Agreement', 'Last_First (ORG) GEN User Agreement DDMMMYYYY'],
  ['General And Privileged Agreement', 'Last_First (ORG) GEN and PRIV Agreement DDMMMYYYY'],
  ['8140 Certification Memo', 'Last_First (ORG) 8140 Cert Memo DDMMMYYYY'],
  ['Privileged User Training', 'Last_First (ORG) PRIV Training Cert DDMMMYYYY'],
  ['DTA Training', 'Last_First (ORG) DTA Training Cert DDMMMYYYY'],
  ['DTA Agreement', 'Last_First (ORG) DTA Agreement DDMMMYYYY'],
];

export default function Guide() {
  return <main className="guide">
    {/* Plain anchor keeps the same guide compatible with the portable Vite build. */}
    {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
    <a href="/">← Return to the Tracker</a>
    <header><p>Reference</p><h1>User Guide</h1></header>
    <nav>{['Getting Started','Systems','Users','Evidence','Sync & Backup','Exports & Notifications','Archive'].map(x=><a key={x} href={`#${x.toLowerCase().split(' ')[0]}`}>{x}</a>)}</nav>
    <section id="getting"><h2>1. Getting Started</h2><ol><li>Open the tracker in Chrome or Edge.</li><li>Select an information system.</li><li>Map the shared evidence root and approve folder access.</li><li>Click Sync and review the Current, Missing, and Overdue totals.</li><li>Click the Missing or Overdue total to filter affected users and prepare notifications.</li></ol><aside>On another computer, select the same shared folder and click Sync. Folder access must be approved on each computer.</aside></section>
    <section id="systems"><h2>2. Manage Information Systems</h2><p>Use <b>Manage systems</b> to add a system, set its type and organization, archive it, or unarchive it. Archiving locks the system and its users while preserving all records.</p></section>
    <section id="users"><h2>3. Add and Update Users</h2><p>Map the shared folder, select an active system, and choose <b>Add user</b> in the User Directory header. General, Privileged, and DTA users receive the appropriate evidence requirements.</p><h3>Upload and Store New-User Evidence</h3><ol><li>Enter the user&apos;s identity, organization, email, role, and Privileged User Type where applicable.</li><li>Upload the original document for every displayed evidence requirement. Do not upload an existing ZIP.</li><li>Choose <b>Add user</b>. The tracker compresses each document into its own ZIP before storing it.</li><li>The files are saved under <code>User Evidence / Information System / Organization / Last_First</code> inside the mapped shared folder.</li></ol><aside>Each ZIP retains the original evidence filename, including its artifact keywords and date. Missing and Overdue validation therefore continues to work against the stored ZIP filename.</aside><p>The User Directory can be filtered by role and Privileged User Type, and each user&apos;s privileged types appear in the results. It displays only document categories required by every user currently shown. Privileged users require the privileged agreement, 8140 memo, and Privileged User Training certificate. DTA users require DTA training and the DTA agreement. Open a User Record to replace evidence, disable or enable access, or modify privileges. Updated documents are compressed and stored, and newly added roles require their additional evidence before submission.</p></section>
    <section id="evidence"><h2>4. Evidence Filename Rules</h2><p>Use the formats below. The validator is intentionally flexible: it checks the user’s last name, the key artifact words, and a compact date such as <b>24AUG2026</b>. Invalid or absent evidence is Missing; valid evidence older than one year is Overdue.</p><div className="formats">{formats.map(([label,format])=><div key={label}><span>{label}</span><code>{format}</code></div>)}</div></section>
    <section id="sync"><h2>5. Shared-Folder Sync, Audit Logs, and Backups</h2><p><b>Map shared folder</b> authorizes the common evidence root. If that folder already contains a tracker manifest, the shared systems and users are loaded before anything is written. <b>Sync</b> reloads the shared manifest, scans every subfolder, maps matching filenames to users, updates the manifest, and refreshes today’s CSV in the <code>backup</code> folder.</p><p>Only one operator can modify a mapped tracker at a time. The app maintains a lightweight session lease in the shared folder. After 15 minutes without activity, the operator is disconnected and must choose <b>Yes, reconnect me</b>. Reconnection is allowed only when another operator is not active.</p><p>Consequential changes—including system administration, user and privilege changes, evidence storage, exports, and synchronization—belong in one daily text file in <code>Audit Logs</code>. Viewing, searching, filtering, and theme changes are excluded.</p></section>
    <section id="exports"><h2>6. Exports and Notification Messages</h2><h3>Export CSV Results</h3><p>Filter by information system, organization, Privileged User Type, status, and one or more artifact types. The Privileged User Type value is included in every CSV row. Archived systems are labeled Active or Archived in every exported row.</p><h3>Prepare Missing or Overdue Notifications</h3><ol><li>Click the <b>Missing</b> or <b>Overdue</b> summary card on the main page. The selected status is applied automatically.</li><li>Select the information system and organization to contact.</li><li>Select exactly one artifact type. The recipient list immediately changes to users whose selected artifact has that status.</li><li>Review the recipient count and matched users. Disabled users and users in archived systems are excluded.</li><li>Use <b>Copy scripted message</b> for an individual notice, or <b>Copy BCC list</b> to copy every matched address.</li><li>Choose <b>Open Outlook Email</b> to create a draft with matched addresses in BCC and a subject and message naming the selected artifact.</li><li>Review the Outlook draft, make any required organizational edits, and send it manually.</li></ol><aside>The tracker never sends email automatically. Outlook must be configured as the computer&apos;s email handler for the draft button to open it.</aside></section>
    <section id="archive"><h2>7. Review Archived Records</h2><p>Archived systems and users remain available as locked, read-only history. Unarchive the system to restore normal editing.</p></section>
    <footer>This application supports NIST SP 800-53-aligned recordkeeping. Formal compliance depends on organizational policies, deployment, access controls, and assessment.</footer>
  </main>;
}

